### ISSUE TITLE
[1.21.1] Anyway to customize shading or edit darkness hardness?

### ISSUE THREAD

**Issue by Cixon** [JonasThanner/Biome-True-Darkness#2]
Hey there! I came to suggest a few things but ultimately, I'm experiencing one minor issue with your mod.
It performances great and is compatible with all the mods in my pack *(so far)* but I'm trying to emulate Minecraft 's Legacy Console Nether which is moderately darker than java's.

Was wondering if you could add a way to modify the darkness hardness or possibly make accommodations for the Nether?

# Here's the visual analyze of what I mean:
![2024-10-17 22_17_27-Greenshot](https://github.com/user-attachments/assets/e0ce19db-b7ba-4c1d-9edf-32a0a6ee8f23)
![p4j](https://github.com/user-attachments/assets/62ea9bab-6f26-40f8-91d2-97b9e961b735)

### Configuration I used:
[darkness-biomes.json](https://github.com/user-attachments/files/17427806/darkness-biomes.json)
[darkness-client.txt](https://github.com/user-attachments/files/17427811/darkness-client.txt)

**Comment by Cixon** [comment]
It’s nearly perfect but in places where there is no light sources, it’s completely black which is not ideal for the vision i’m going for. If this could get fixed specifically for the Nether or a way to edit the darkness hardness level, this could uplift this issue.

Please look into it if possible, thank you for your time!

**Comment by JonasThanner** [comment]
Thank you for the suggestion. Im looking into it

**Comment by Cixon** [comment]
> Thank you for the suggestion. Im looking into it

Thank you for your time and consideration! 🤞 for a fix

**Comment by Cixon** [comment]
If you want to test it on my modpack I just uploaded a update with the mod included.
**Here:** `https://modrinth.com/modpack/project-4j/version/TU14-prerelease-1.3.0`

**Comment by JonasThanner** [comment]
@Cixon Something like this?
Top is 0.5f brighness increase
Middle is 0, i.e default and Bottom is 1.0 ie no darkness at all
![2024-10-22_22 47 24](https://github.com/user-attachments/assets/a407277e-3104-4c85-ae84-e5c8ad0f4659)
![2024-10-22_22 48 33](https://github.com/user-attachments/assets/201c280d-9745-40c5-b5c9-4ceb0c75773a)
![2024-10-22_22 46 43](https://github.com/user-attachments/assets/c4e7f8c2-31e4-4d2a-b0fb-adcad453aa89)

**Comment by Cixon** [comment]
0.2 * would be a good middle ground

**Comment by Cixon** [comment]
> 0.2 * would be a good middle ground

if not possible, 0.5 is fine

**Comment by JonasThanner** [comment]
@Cixon the value is configurable. Its in the latest release for 1.21.1. I consider this closed now :)

**Comment by Cixon** [comment]
perfect thank you!
