### ISSUE TITLE
Add config option for less harsh linear darkness transition across moon phases?

### ISSUE THREAD

**Issue by minh-craft** [JonasThanner/Biome-True-Darkness#3]
Hi, I think it would be really nice to have a config option for smoother light to dark transitions across moon phases.
I've been trying to make this change myself, but I'm having a lot of trouble with getting started with setting up the dev environment. 

Right now, I believe the light level from the moon is squared, so night 2 with 0.75 brightness actually becomes 0.5625 brightness. and night 3 with 0.5 brightness becomes 0.25 brightness. (I haven't actually been able to test so I could be wrong)
Personally I'd prefer a smoother linear transition so night 2 actually is 0.75 brightness and night 3 is actually 0.5 brightness so that there is a contrast between the darker moon phases and brighter moon phases.

I think this is the line responsible for this behavior:

https://github.com/JonasThanner/Biome-True-Darkness/blob/b71b397e7427a2edb55eba2196d1d85f9c90c45c/common/src/main/java/grondag/darkness/Darkness.java#L170

Would you consider adding this feature?
I'd also be happy to try adding it myself, if you'd be willing to give me some pointers on how to set up the dev environment so I can test it myself!

**Comment by JonasThanner** [comment]
Thanks for reporting back. Im looking into it. Will probably take a while tough (~2 weeks). If you do manage to set up the dev enviroment id be happy to accept a pull request

**Comment by minh-craft** [comment]
Actually, I may have just figured out my dev environment stuff, I was on the old 1.19 branch which didn't have any of the genIntellijRuns and runClient tasks I was trying to find

**Comment by JonasThanner** [comment]
Thanks for the changes. How would you like to be credited on Modrinth / curseforge?

**Comment by minh-craft** [comment]
Oh, I appreciate the offer, but there’s no need! I’m just grateful you were willing to add the changes I wanted. Thanks!
